apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Base de données 
  postgres-db: "petite_maison"
  postgres-user: "dev"
  postgres-password: "devpass"
  # Sécurité JWT
  jwt-secret: "super-secret-access-key-64chars-minimum-random-key-change-me-12345"
  jwt-refresh-secret: "super-secret-refresh-key-64chars-minimum-random-key-change-me-12345"